### ISSUE TITLE
Tutorial Error

### ISSUE THREAD

**Issue by MADONOKOUKI** [Phylliade/ikpy#101]
Hi, my name is koki.
I got an error like that. I use anaconda3-5.3.1 and Python 3.5.6.
I want to know why was it error happened?

`
>>> import ikpy
>>> my_chain = ikpy.chain.Chain.from_urdf_file("model.urdf")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'ikpy' has no attribute 'chain'
`

**Comment by Benoit-LdL** [comment]
Same issue here, I can't seem to get any submodule of ikpy to work. I'm running version 3.0.1 with python 2.7.12...
Tried some of the test scripts without any luck
`
from ikpy.link import OriginLink, URDFLink
--> ImportError: No module named link

from ikpy.chain import Chain
--> ImportError: No module named chain

import ikpy.utils.plot as plot_utils
--> ImportError: No module named utils.plot
`

Thanks in advance for your help!
Kind regards,
Benoît

**Comment by Phylliade** [comment]
Hello @MADONOKOUKI @Benoit-LdL,

How are you installing IKPy?
(On my side, i'm not able to reproduce this issue)

Besides, @MADONOKOUKI, what version of IKPy are you using?

**Comment by KyleORourke2** [comment]
I'm having the same issue. I'm using the latest version of ikpy v3.1 with Python 3.8.3. I've tried both 'pip install ikpy' and from source with the same error: 

> module 'ikpy' has no attribute 'chain'

**Comment by Zju-George** [comment]
@Phylliade @Benoit-LdL @MADONOKOUKI @KyleORourke2 Check out this: https://stackoverflow.com/questions/8899198/module-has-no-attribute
In pyik the submodule is not directory but pyfile so it is not imported automatically.
A quick solution, add `import` in __init__.py like this
![image](https://user-images.githubusercontent.com/33959089/106726280-29809000-6645-11eb-8de8-7749fb6531db.png)
Then it will work.
![image](https://user-images.githubusercontent.com/33959089/106726517-6d739500-6645-11eb-868e-33135ee9e0a5.png)

**Comment by Piit3r** [comment]
Same here in local.
I also tested on google colab :
I imported de Quickstart file. Just run `pip install ikpy` on top and execute

**Comment by Phylliade** [comment]
Hello @MADONOKOUKI, this has been fixed in master, you call pull the latest ipynb file and this will work.
No need to update IKPy.
