### ISSUE TITLE
Changing the optimization algorithm

### ISSUE THREAD

**Issue by ger01d** [Phylliade/ikpy#108]
Is it possible to change the optimization algorithm with a function call, or is it only possible to statically change line 134 in _inverse_kinematics.py_?
With _L-BFGS-B_ and joint boundaries I noticed a jumpy behavior in the end effector positions of the kinematic model, so I changed it to _SLSQP_.

The models, where this problems come up, can be found here:
[quadruped model](https://github.com/ger01d/kinematic-model-opencat)

**Comment by Phylliade** [comment]
Hello @ger01d,

Did changing the optimization method to  SLSQP solve your issue?

In the meantime, I will add a method to select the optimization algorithm in the constructor

**Comment by ger01d** [comment]
Hi @Phylliade,

yes, changing to SLSQP solved the problem. Thanks for bringing this feature into the code.

**Comment by Phylliade** [comment]
Hello @ger01d, 
Support for customizable optimization algorithms has landed on master and on `v3.2`. Just use the `optimization_method` of the `Chain.inverse_kinematics`.

**Comment by MarcDcls** [comment]
Hi @Phylliade, 

It seems that the argument `optimization_method` is never used in `inverse_kinematic_optimization` , can we really change the optimization algorithm through this argument ?

**Comment by Phylliade** [comment]
Hello @MarcDcls , yep you're right, this parameter is not used anymore

**Comment by Phylliade** [comment]
Do you need access to the old optimization method, based on L-BFGS-B?

In https://github.com/Phylliade/ikpy/issues/123, access to L-BFGS-B is required because the new optimization method it breaks performances on some cases (to be dug)

**Comment by MarcDcls** [comment]
Hi @Phylliade, 

I wanted to test several optimization methods to find the one that fit the best my problem. I've managed to do it by myself so I don't have issue anymore. Thank for your help
