### ISSUE TITLE
Issue in Chain.plot method when ax = None

### ISSUE THREAD

**Issue by AntonioConsiglio** [Phylliade/ikpy#119]
![image](https://user-images.githubusercontent.com/77753494/154771442-639bda51-c992-4d6f-aee9-b2b0009445b2.png)

the output of the plot.init_3d_figure() should be --> fig, ax but only ax is written. As you can see from the screenshot it is useful to add the _ to avoid the issue.

**Comment by Phylliade** [comment]
Hello @AntonioConsiglio,

Thanks for the feedback!

Why do you need the `fig` object? I've looked and it's not used in the [code](https://github.com/Phylliade/ikpy/blob/f2aa3be1b62d901098035ee13f6850b75ad9416a/src/ikpy/chain.py#L195)

**Comment by AntonioConsiglio** [comment]
Hello @Phylliade , of course it's not in the core.
But if you see the function called " init_3d_figure()" the output is fig,ax. The only thing we need is ax, so we need to take the second output but in that case in the variable ax is stored the fig output insted of ax.
Here the link to the [code](https://github.com/Phylliade/ikpy/blob/f2aa3be1b62d901098035ee13f6850b75ad9416a/src/ikpy/utils/plot.py#L111)

I hope it is clear.

**Comment by Phylliade** [comment]
ah ok! sorry! yep clear
I'll psuh a fix
