### ISSUE TITLE
how to get pose?

### ISSUE THREAD

**Issue by luoww1992** [Phylliade/ikpy#127]
now i have a human 3d keypoints file.
how can i get the pose euler rotation angle or quaternion with parent-child relationship like smpl pose, 
i want to use it to drive skeleton in blender or UE4.
i have tested to make bvh file to use it in blender, but i want to run it in real time, so ineed to change the method.
can you give me some adviences?

**Comment by coder-rakeshpaul** [comment]
> now i have a human 3d keypoints file. how can i get the pose euler rotation angle or quaternion with parent-child relationship like smpl pose, i want to use it to drive skeleton in blender or UE4. i have tested to make bvh file to use it in blender, but i want to run it in real time, so ineed to change the method. can you give me some adviences?

were you able to figure this out? I'm also interested in doing something similar
