### ISSUE TITLE
How to add constrains to the chain to ensure the robot arm is always above the workbench?

### ISSUE THREAD

**Issue by FredTrumpSenior** [Phylliade/ikpy#130]
How can I add constrains to ensure that the arm is always above the workbench without colliding with it. 

![1673507962687](https://user-images.githubusercontent.com/118232801/212002925-f2fd1d99-5610-42de-bc7b-1c4c14b90c36.jpg)

**Comment by Phylliade** [comment]
Hello @FredTrumpSenior,

For the moment, there is no direct way to add constraints on links positions. 

However you can add a constraint in joint angles by defining joint bounds:
For example you can try to [add a bound](https://github.com/Phylliade/ikpy/blob/a32b3f3d3a02858b8e727941782a703e14e291b0/src/ikpy/link.py#L83) for the 3rd joint (the joint before the link that goes into the workbench) to be only positive, this way the link will never be in the negative Zs:

**Comment by FredTrumpSenior** [comment]
Thanks for your kind reply
