### ISSUE TITLE
 AttributeError: 'Robot' object has no attribute 'goto_target'

### ISSUE THREAD

**Issue by studywolf** [Phylliade/ikpy#15]
I'm in the Inverse kinematics with the ErgoJr tutorial, and in cell 7 i'm getting 

```
----
AttributeError                            Traceback (most recent call last)
<ipython-input-7-d1db5050b446> in <module>()
----> 1 poppy.goto([-0.00670386, -0.17439168,  0.15083097])

AttributeError: 'Robot' object has no attribute 'goto'
```

I've tried to track this down but without luck, can't find where the Robot object is stored, any ideas?

**Comment by Phylliade** [comment]
I'm on it, i'll check as soon as i have some time!
Did you manage to get the other notebooks (like this [one](https://github.com/Phylliade/ikpy/blob/master/tutorials/ikpy/Quickstart.ipynb)) to work?

Thanks again for your feedback!

**Comment by studywolf** [comment]
great thanks! and yup that  other one works perfect!

**Comment by Phylliade** [comment]
This is now fixed : the object to use for Inverse Kinematics is actually `poppy.chain`, (not `poppy` itself).

**Comment by studywolf** [comment]
awesome, thanks!

**Comment by Phylliade** [comment]
Hi again Studywolf,
Is this issue closed? (Just checking which issues require some work!)

**Comment by studywolf** [comment]
oh, yes! thanks!
