### ISSUE TITLE
IT DOES NOT RESPECT LIMITS

### ISSUE THREAD

**Issue by matteopantano** [Phylliade/ikpy#32]
Hi,

As written on the tittle, the tool does not respect limits sent by URDF, I do not know if it is a problem of my `URDF` of `function call`, can anyone give me hints?

[URDF](https://github.com/Phylliade/ikpy/files/836786/youbot.txt)

_function call_
`my_chain = ikpy.chain.Chain.from_urdf_file("/home/matteo/rover_ws/urdf/youbot.urdf", base_elements=["base_link", "arm_joint_0", "arm_link_0", "arm_joint_1", "arm_link_1", "arm_joint_2", "arm_link_2", "arm_joint_3", "arm_link_3", "arm_joint_4", "arm_link_4", "arm_joint_5", "arm_link_5"])
		ax = matplotlib.pyplot.figure().add_subplot(111, projection='3d')`

**Comment by Phylliade** [comment]
Actually, this functionality is working without problems on tested robots (it's mandatory to have such limits on the [poppy torso arms](https://www.poppy-project.org/en/), to avoid breaking them.

It can be related to your URDF : You can have a look at https://github.com/Phylliade/ikpy/blob/master/resources/poppy_torso.URDF#L329 to compare with yours.

When it's working, feel free to do a pull request to add the URDF of your robot to the [resources](https://github.com/Phylliade/ikpy/tree/master/resources) directory of the repo, it will help supporting the robot!
