### ISSUE TITLE
The Program Don't respect the Joint's Limit

### ISSUE THREAD

**Issue by Ivanildo0303** [Phylliade/ikpy#34]
Good Night,

I'm using the lib for a project where I build my own URDF file. But when I use the program the angles wich return are bigger then my servo drivers limits. How can I fix It.

My URDF File is attached in txt because Git doesn't support URDF.
[Xinui.txt](https://github.com/Phylliade/ikpy/files/949399/Xinui.txt)

Please I need a Help.

@Phylliade @pierre-rouanet @gitter-badger @buschbapti 

 @Thanks

**Comment by Ivanildo0303** [comment]
Good Night,

I having a doubt, how can I limit the space work only to +z, because there is some links, going to under normal line Z.

Thanks

**Comment by Phylliade** [comment]
Bounds are now taken into account thanks to #42
