### ISSUE TITLE
is there a way to hold the tcp even/horizontal??

### ISSUE THREAD

**Issue by EdoFZI** [Phylliade/ikpy#41]
I am looking for a way to keep my tool-center-point (tcp) even to move for example a glass of water without loosing water. Is there a way in ikpy to solve such problems??

**Comment by Phylliade** [comment]
Rotation is a feature planned in a next milestone!

**Comment by Phylliade** [comment]
You can now use the orientation feature to keep your glass vertical!

https://github.com/Phylliade/ikpy/blob/master/tutorials/Orientation.ipynb
