### ISSUE TITLE
Origin Link is not working

### ISSUE THREAD

**Issue by HarithKK** [Phylliade/ikpy#43]
We check our handmade robot arm with ikpy. but when we use OriginLink it was not giving us the exact value.

then we use this

from ikpy.chain import Chain
from ikpy.link import OriginLink, URDFLink
from ikpy import geometry_utils
import numpy as np
import math

robotarm = Chain(name='left_arm', links=[
    
    URDFLink(
      name="mx",
      translation_vector=[0,0, 0],
      orientation=[0, 0, 0],
      rotation=[0, 0, 1],
    ),
    URDFLink(
      name="mb",
      translation_vector=[42,32.42, 0],
      orientation=[0, 0, 0.658],
      rotation=[0, 0, 1],
    ),
    URDFLink(
      name="mm",
      translation_vector=[-32.7,25.54, 0],
      orientation=[0, 0, 2.47],
      rotation=[0, 0, 1],
    )
    
])

tvalues = geometry_utils.to_transformation_matrix([-9.4,66.64,0])
tmax =  robotarm.inverse_kinematics(tvalues)
mb_val =math.degrees(tmax[0] + 0.658)
mm_val =math.degrees(tmax[1] + 2.47)
print  mb_val
print mm_val

print tmax

**Comment by Phylliade** [comment]
Hello @HarithKK, could you provide the output of your script?
