### ISSUE TITLE
Target with rotation

### ISSUE THREAD

**Issue by snape6666** [Phylliade/ikpy#48]
Hey guys,
is there a way to get a solution for a rotated target? We would like to use ikpy for our robotik, animations in unity, but therefor we need to rotate the target.

Any ideas?

**Comment by Phylliade** [comment]
Support for rotation is planned in a future milestone!

**Comment by Phylliade** [comment]
You can apply orientation with the latest release!

https://github.com/Phylliade/ikpy/blob/master/tutorials/Orientation.ipynb
