### ISSUE TITLE
Create Chain method will not make chain from URDF file and also does not throw an error

### ISSUE THREAD

**Issue by Lutarp** [Phylliade/ikpy#56]
Hi, while using the library on a raspberry PI, the .from_urdf_file() method seems to run fine on the tutorial file poppy_ergo.URDF. But when given my URDF file to create a chain it does not actually create a chain, merely creating a simple base_link fill in. It also does not throw any error when trying to parse the file, it simply takes it and does not parse any data.
![Screenshot (8)](https://user-images.githubusercontent.com/16502495/58885848-e4a69800-86b0-11e9-9319-26f53981f844.png)
![Screenshot (9)](https://user-images.githubusercontent.com/16502495/58885855-e7a18880-86b0-11e9-93b5-f93aa2200926.png)

**Comment by Phylliade** [comment]
Hey @Lutarp, could you paste your URDF file?

**Comment by jurka14** [comment]
Hi, I have been having the same problem with my URDF file. Here it is:

`
<?xml version="1.0" encoding="utf-8"?>

<robot
  name="Rameno_sestava.SLDASM">
  <link
    name="base_Link">
    <inertial>
      <origin
        xyz="0.0375 0.00734688456192442 1.24826504699513E-09"
        rpy="0 0 0" />
      <mass
        value="0.010277230998552" />
      <inertia
        ixx="1.092531894428E-05"
        ixy="1.4467160407856E-21"
        ixz="-2.20849246804654E-13"
        iyy="1.30777709748279E-05"
        iyz="1.98533463602263E-13"
        izz="3.52427256535382E-06" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://Rameno_sestava.SLDASM/meshes/base_Link.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.627450980392157 0.627450980392157 0.627450980392157 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://Rameno_sestava.SLDASM/meshes/base_Link.STL" />
      </geometry>
    </collision>
  </link>
  <link
    name="Rotating_base_Link">
    <inertial>
      <origin
        xyz="-0.0310067493964589 0.0356912345580542 -1.40021952366176E-11"
        rpy="0 0 0" />
      <mass
        value="0.0842744537549328" />
      <inertia
        ixx="3.72775016732398E-05"
        ixy="9.39829888441467E-06"
        ixz="3.46042252569305E-10"
        iyy="3.97404908918724E-05"
        iyz="2.56760938255436E-10"
        izz="3.12686222723885E-05" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://Rameno_sestava.SLDASM/meshes/Rotating_base_Link.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.627450980392157 0.627450980392157 0.627450980392157 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://Rameno_sestava.SLDASM/meshes/Rotating_base_Link.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="Rotating_base_Joint"
    type="revolute">
    <origin
      xyz="0.0375 0 0.02725"
      rpy="1.5708 0 -1.7801" />
    <parent
      link="base_Link" />
    <child
      link="Rotating_base_Link" />
    <axis
      xyz="0 1 0" />
    <limit
      lower="-0.99466"
      upper="3.7177"
      effort="0"
      velocity="0" />
  </joint>
  <link
    name="First_arm_Link">
    <inertial>
      <origin
        xyz="0.0437860972682325 -6.93889390390723E-17 0.00326140914475796"
        rpy="0 0 0" />
      <mass
        value="0.00971683868174796" />
      <inertia
        ixx="7.83831769487946E-07"
        ixy="-4.2086949566698E-21"
        ixz="-9.69461623635794E-07"
        iyy="1.45073308706587E-05"
        iyz="-1.6940658945086E-21"
        izz="1.37271429156764E-05" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://Rameno_sestava.SLDASM/meshes/First_arm_Link.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.627450980392157 0.627450980392157 0.627450980392157 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://Rameno_sestava.SLDASM/meshes/First_arm_Link.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="First_arm_Joint"
    type="revolute">
    <origin
      xyz="-0.041953 0.04825 0"
      rpy="-1.5708 0 1.0223" />
    <parent
      link="Rotating_base_Link" />
    <child
      link="First_arm_Link" />
    <axis
      xyz="0 1 0" />
    <limit
      lower="-2.1451"
      upper="1.171"
      effort="0"
      velocity="0" />
  </joint>
  <link
    name="Second_arm_Link">
    <inertial>
      <origin
        xyz="0.00025004731122083 0.0160527989756333 -0.00621904010911814"
        rpy="0 0 0" />
      <mass
        value="0.00540843852447768" />
      <inertia
        ixx="1.72506728064076E-06"
        ixy="2.22046609719669E-13"
        ixz="-2.60877877238601E-12"
        iyy="3.12175046483521E-06"
        iyz="-1.12477213972645E-07"
        izz="2.26920711165746E-06" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://Rameno_sestava.SLDASM/meshes/Second_arm_Link.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.627450980392157 0.627450980392157 0.627450980392157 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://Rameno_sestava.SLDASM/meshes/Second_arm_Link.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="Second_arm_Joint"
    type="revolute">
    <origin
      xyz="0.108 0 0.0080444"
      rpy="-0.29468 0 -1.5708" />
    <parent
      link="First_arm_Link" />
    <child
      link="Second_arm_Link" />
    <axis
      xyz="1 0 0" />
    <limit
      lower="-0.83978"
      upper="0.99282"
      effort="0"
      velocity="0" />
  </joint>
  <link
    name="Barrel_part_Link">
    <inertial>
      <origin
        xyz="0.000250002003399863 -0.00152313111878316 -0.0785733559312348"
        rpy="0 0 0" />
      <mass
        value="0.00989593755673276" />
      <inertia
        ixx="4.34247891884215E-06"
        ixy="-7.69874870075889E-10"
        ixz="3.92689246468547E-08"
        iyy="5.68213593986647E-06"
        iyz="2.00120730440082E-08"
        izz="2.42783408470459E-06" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://Rameno_sestava.SLDASM/meshes/Barrel_part_Link.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.627450980392157 0.627450980392157 0.627450980392157 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://Rameno_sestava.SLDASM/meshes/Barrel_part_Link.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="Barrel_part_Joint"
    type="revolute">
    <origin
      xyz="0.00025 0.0187 0"
      rpy="-3.1416 0 2.8007" />
    <parent
      link="Second_arm_Link" />
    <child
      link="Barrel_part_Link" />
    <axis
      xyz="0 0 1" />
    <limit
      lower="-2.6971"
      upper="2.0153"
      effort="0"
      velocity="0" />
  </joint>
  <link
    name="End_point_Link">
    <inertial>
      <origin
        xyz="-2.22044604925031E-16 -0.00570377926609689 0.00939618564437633"
        rpy="0 0 0" />
      <mass
        value="0.00307447825496952" />
      <inertia
        ixx="4.4824017317466E-07"
        ixy="3.49070218497378E-22"
        ixz="3.57342024622908E-22"
        iyy="6.59712013045634E-07"
        iyz="-7.88806742587389E-08"
        izz="4.52524113194771E-07" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://Rameno_sestava.SLDASM/meshes/End_point_Link.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.627450980392157 0.627450980392157 0.627450980392157 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://Rameno_sestava.SLDASM/meshes/End_point_Link.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="End_point_Joint"
    type="revolute">
    <origin
      xyz="0 -0.003 -0.12435"
      rpy="-2.1581 0 -3.1416" />
    <parent
      link="Barrel_part_Link" />
    <child
      link="End_point_Link" />
    <axis
      xyz="1 0 0" />
    <limit
      lower="-0.98347"
      upper="2.1581"
      effort="0"
      velocity="0" />
  </joint>
</robot>
`
