### ISSUE TITLE
URDF files when imported, Import the joints as the links

### ISSUE THREAD

**Issue by Lutarp** [Phylliade/ikpy#57]
When loading a URDF file to make a chain, the joints are loaded as URDF links rather than the actual links.

**Comment by Phylliade** [comment]
That's indeed a difference in nmaings between ikpy and URDF: 

* URDF joints = IKPY links
* IKPY does not use URDF links

**Comment by Phylliade** [comment]
This will be tackled in a future release. For the moment, this is documented here:

https://github.com/Phylliade/ikpy/blob/master/src/ikpy/chain.py#L159-L160
