### ISSUE TITLE
Definition of the robot

### ISSUE THREAD

**Issue by MarcGondran** [Phylliade/ikpy#62]
Hi,

Thank you for your work. I have few questions about the use of this library.

- I have concern about the definition of the robot with DH-Table. It seems that the function to crate links with DH-Parameters is not implemented yet. Do you know a way to transform easily DH-Parameters into URDF parameters (Translation_vector, orientation and rotation) ?

- My robot is a KUKA KR-100 HA with a 7th prismatic joint. I haven't found a way to define a prismatic joint, is there a solution in your program ? And is the program able to compute inverse solution for redundant robot ?

Thank you very much

Marc

**Comment by Phylliade** [comment]
Hey,

* Conversion from DH to URDF: Never tried it, but there are solutions online, like https://github.com/AdoHaha/DH2URDF. Tell me if this works!
* I've just added prismatic joints support in the TODO list, 
* For the redundant robot, that's a good question: do you have any examples of redondant robot for which we could apply the inverse kinematics?

**Comment by Tanneguydv** [comment]
@MarcGondran 
I've written some code to resolve the problem of creating a chain link from DH parameters table, see https://github.com/Phylliade/ikpy/pull/143

**Comment by AdvaitChandorkar07** [comment]
@MarcGondran Since it is using an iterative method to calculate the angles it should solve for redundant robots though there is no guarantee of optimal solution also you should try to check the solution just in case with forward kinematics. I am not sure about the prismatic joint though, 7R robot should get an inverse kinematics solution

**Comment by Phylliade** [comment]
DH support is now included in the last release!
