### ISSUE TITLE
Ways to deal with self-collisions?

### ISSUE THREAD

**Issue by beduffy** [Phylliade/ikpy#66]
Hello, great library, thanks for your work!

Is there any way to ensure that the joint angles returned from inverse kinematics won't result in a self-collision? I have my own functions for detecting these but how could I influence or change the optimisation to avoid them?

Should I change link bounds as the arm moves and is this possible/advisable?

**Comment by Phylliade** [comment]
Hey @beduffy,

Currently there is no support for avoiding self-collisions.

However it would be interesting to add this feature!

In order to see where we can start, could you past/explain a bit your self-collision avoidance functions?

**Comment by beduffy** [comment]
![image](https://user-images.githubusercontent.com/9202993/71004847-766c7480-20da-11ea-8fd3-3a25590264e4.png)

Hopefully this image makes it clearer, the blue line is going through the other blue line. If I told the real robot arm to do this there would be damage. 

Generally it's quite easy to detect collisions between line segments e.g. don't include the exact endpoints since two lines share joint locations, loop through each line segment against every other line segment and return True if there is a collision.

**Comment by Phylliade** [comment]
Got it!

Yep, that would be indeed possible to add a collision detection function, as described.

Additionally, there is also the topic of collision avoidance, aka, proposing an IK solution that avoids collisions (e.g. not only detecting collisions, but also avoid them). Would you have any ideas on how to implement this?

**Comment by beduffy** [comment]
I know you use scipy.optimise underneath so this is akin to a Jacobian/Least Squares method but in the past I've been confused over exactly how ikpy is "symbolic" or maybe it uses sympy for something else. For jacobian methods it's much harder avoid collisions because we have to constrain the optimisation away from these regions and nothing is guaranteed. 

Even just avoiding joint limits is a pain, this master's thesis goes deeper into that: https://pdfs.semanticscholar.org/673d/1b06d968216933d298e0eecff9fa20a2514b.pdf

I prefer analytical/geometric methods since they are faster and it's possible to directly get multiple solutions out of them. But if I was to make a jacobians method to work with collisions it quickly turns into a motion planning problem and you would have to look into OMPL, MoveIt and other libraries. Some methods generally try thousands of configurations close to the target and slowly prune out the configurations which are in collision with objects. Trac-ik (https://arxiv.org/pdf/1811.00600.pdf) and relaxedIK are also other resources. Sorry I can't be of more help.

**Comment by Phylliade** [comment]
Thanks for the resources, will dig into that!
