### ISSUE TITLE
Can you find certain joint locations?

### ISSUE THREAD

**Issue by AhmetMericOzcan** [Phylliade/ikpy#68]
I know that this library can find end effector position, with F.K. However I would like to know whether you can find certain joint position and orientation in space?

Ex. I have a 6 DOF robot, I would like to find position of 3rd joint in space.

**Comment by Phylliade** [comment]
Yep, and it's easy!
Just put the `full_kinematics` attribute to `True` in `Chain.forward_kinematics`
(cf https://github.com/Phylliade/ikpy/blob/master/src/ikpy/chain.py#L48)
