### ISSUE TITLE
ikpy is not pure python because it depends on numpy and scipy

### ISSUE THREAD

**Issue by nevercast** [Phylliade/ikpy#70]
Since numpy and scipy are not pure python (have c / native dependencies), ikpy cannot be considered pure python. (Unless a slower implementation existed that did not depend on numpy or scipy.

**Comment by Phylliade** [comment]
Well you're right, there are C dependencies, but IKPy codebase itself is in pure python.

(executing C code is not a problem per se, the Cpython runtime is in C ;) )

**Comment by nevercast** [comment]
> (executing C code is not a problem per se, the Cpython runtime is in C ;) )

I was looking for a pure Python IK library that I could run on MicroPython (embedded systems), your library came up but unfortunately MicroPython does not provide scipy, and numpy is very limited at this time. 

I'm not trying to be pedantic, I really did want to use it in a purely Python environment ❤️

**Comment by Phylliade** [comment]
Ah ok got it!

I suggest adding a FAQ about dependencies and the supported platforms.

Would it solve the issue?
