### ISSUE TITLE
Can I use this lib for computing 3D coordinates from 2D image coordinates?

### ISSUE THREAD

**Issue by JasOlean** [Phylliade/ikpy#72]
Does this lib work for Hand Joints (21 joints)?
I want to use this lib to compute 3D coordinates from 2D image coordinates using inverse kinematics.
So, can I use this lib for Hand Joints?

**Comment by Phylliade** [comment]
Hello @JasOlean,

In which format do you have your hand?

Are these 2d image coordinate a projection ?
